
<HTML>
<HEAD>



<FRAMESET ROWS="100, *"  BORDER="0" FRAMESPACING="0" NORESIZE SCROLLING="NO">
    <FRAME SRC="lin1.jsp">

    <FRAMESET COLS="230, *">
        <FRAME SRC="col1.jsp" NORESIZE SCROLLING="NO"> 
        <FRAME SRC="palavra" NAME="conteudo"> 
    </FRAMESET> 

</FRAMESET> 

<TITLE>TESTE DE FRAMES</TITLE>
</HEAD>

</HTML>


